### ISSUE TITLE
unable to download Cognitive-Common-Windows folder contents

### ISSUE THREAD

**Issue by fj4870** [Microsoft/Cognitive-Common-Windows#3]
source location https://github.com/Microsoft/Cognitive-vision-windows

**Comment by huxuan** [comment]
Have you tried `git submodule init & git submodule update`? `Cognitive-Common-Windows` is a submodule of `Cognitive-Vision-Windows`, for more specific information about `submodule`, please refer to official git document here [1]. If you still have any further problem, feel free to follow up in this thread.

[1] https://git-scm.com/docs/git-submodule

**Comment by fj4870** [comment]
I have downloaded the Computer Vision API client library and example application from https://github.com/Microsoft/Cognitive-vision-windows. Unfortunately content of Cognitive-Common-Windows folder is missing/empty under  downloaded zip.  Request you to please share the complete zip file. Thanks in advance.

**Comment by huxuan** [comment]
It's recommended to use git clone instead of download zip.
`git clone https://github.com/Microsoft/Cognitive-Vision-Windows.git` should work.
I have also tried `Download ZIP` and it do have nothing in the `Cognitive-Common-Windows` folder.
It seems like a bug of github.

**Comment by fj4870** [comment]
Thank You!!!!!! It's working.....

**Comment by huxuan** [comment]
Close as resolved. Feel free to reopen it in case of any further related questions.
